---
- name: Copy kubeadm.yaml file
  ansible.builtin.template:
    src: "./templates/kubeadm.yaml"
    dest: "/etc/kubernetes"


# - name: Copy 10-kubeadm.conf file
#   ansible.builtin.template:
#     src: "./templates/10-kubeadm.conf"
#     dest: "/etc/systemd/system/kubelet.service.d"


# - name: initialize the cluster
#   command: kubeadm init --config /etc/kubernetes/aws.yaml --upload-certs > cluster_initialized.txt
#   args:
#     chdir: $HOME
#     creates: cluster_initialized.txt

- name: initialize the cluster
  shell: kubeadm init --config /etc/kubernetes/kubeadm.yaml --upload-certs
  args:
    creates: $HOME/kubeadm_init
  register: kubeadm_init
  # when: "'/etc/kubernetes/manifests/kube-apiserver.yaml' not in kubeadm_init.stdout"
  # run_once: true
  # ignore_errors: true

- name: Print join commands
  ansible.builtin.debug:
    var: kubeadm_init.stdout
  when: kubeadm_init.stdout == true

- pause:
    minutes: 2

# - name: Store init output
#   action: copy content="{{ kubeadm_init.stdout }}" dest="/etc/kubernetes/kubeadm-init.stdout"
#   when: kubeadm_init.stdout exists
#   ignore_errors: true

- name: create .kube directory
  become: true
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  run_once: true

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    state: link
    owner: ubuntu
    mode: 0644
  run_once: true

- name: install Pod network
  become: true
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml > pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

