---
- name: Restart etcd service
  become: yes
  systemd: 
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Controller services
  become: yes
  ansible.builtin.systemd: 
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

# - name: Restart Nginx service
#   become: yes
#   systemd: 
#     name: nginx
#     state: restarted
#     enabled: yes
#     daemon_reload: yes