---  
    - name: Create ca-authority directory
      ansible.builtin.file:
        path: /tmp/ca-authority
        state: directory
        follow: yes

    - name: Copy to ca-authority directory
      template:
        src: "./templates/{{ item }}.j2"
        dest: "/tmp/ca-authority/{{ item }}"
        mode: +rwx
      loop:
        - certificates.sh
        - kubeconfigs.sh
        - encryption-config.sh
        - kubeconfig-server.sh
  

    - name: Generate certificates
      ansible.builtin.shell: ./certificates.sh
      args:
        chdir: /tmp/ca-authority
        creates: service-account-csr.json

    - name: Generate kubeconfig files
      ansible.builtin.shell: ./kubeconfigs.sh
      args:
        chdir: /tmp/ca-authority
        creates: admin.kubeconfig

    - name: Generate encryption.yaml
      ansible.builtin.shell: ./encryption-config.sh
      args:
        chdir: /tmp/ca-authority
        creates: encryption-config.yaml

    - name: Recursively change permissions of /tmp/ca-authority
      ansible.builtin.file: 
        path: /tmp/ca-authority
        recurse: yes
        mode: '0777'

    - name: Set context for remote access
      ansible.builtin.shell: ./kubeconfig-server.sh
      debugger: always
      args:
        chdir: /tmp/ca-authority