---
- hosts: localhost
- name: workstation assignment
  import_playbook: ../static-assignments/workstation.yaml


- hosts: tag_Name_k8s_cluster_from_ground_up_master_0, tag_Name_k8s_cluster_from_ground_up_master_1, tag_Name_k8s_cluster_from_ground_up_master_2 
- name: master nodes assignment
  import_playbook: ../static-assignments/master.yaml

- hosts: tag_Name_k8s_cluster_from_ground_up_master_0
- name: cluster role binding assignment
  import_playbook: ../static-assignments/rbac.yaml


- hosts: tag_Name_k8s_cluster_from_ground_up_worker_0, tag_Name_k8s_cluster_from_ground_up_worker_1, tag_Name_k8s_cluster_from_ground_up_worker_2
- name: worker nodes assignment
  import_playbook: ../static-assignments/worker.yaml
