---
- name: Copy admin.config needed to create and bind cluster roles 
  copy:
    src: "/tmp/ca-authority/admin.kubeconfig"
    dest: "/home/ubuntu"
    remote_src: no

- name: Checking reachability
  ansible.builtin.command: curl --cacert /var/lib/kubernetes/ca.pem https://{{internal_ip}}:6443/version

- name: Copy binding.sh to master-0
  template:
    src: "./binding.sh"
    dest: "/home/ubuntu"
    owner: ubuntu
    group: ubuntu
    mode: '0777'

- name: Create and bind cluster roles
  ansible.builtin.shell: ./binding.sh
  args:
    chdir: /home/ubuntu
