---
- name: Remove swapfile from /etc/fstab to disable swap
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
     - swap
     - none


- name: Disable swap
  command: swapoff -a


- name: Install required dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - curl
    state: present
    update_cache: yes
    force_apt_get: yes


- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present


- name: add kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    filename: 'kubernetes'


# - name: Create /etc/apt/sources.list.d/kubernetes.list directory
#   ansible.builtin.file:
#     path: /etc/apt/sources.list.d/kubernetes.list
#     state: directory
#     follow: yes

    
# - name: Copy kubernetes.list from templates
#   ansible.builtin.template:
#     src: "./templates/{{ item.src }}.sh"
#     dest: "{{ item.dest }}"
#     loop:
#       - {src: kubernetes.list, dest: /etc/apt/sources.list.d/kubernetes.list}
  # notify: Restart Controller services


- name: Install kubelet, kubeadm,kubectl
  become: true
  apt:
    name:
      - kubelet=1.15.0-00
      - kubeadm=1.15.0-00
      - kubectl=1.15.0-00
    state: present
    update_cache: yes
    force_apt_get: yes



# - name: Hold kubeadm
# - dpkg_selections:
#     name: kubeadm
#     selection: hold
# - dpkg_selections:
#     name: kubelet
#     selection: hold
# - dpkg_selections:
#     name: kubectl
#     selection: hold



- name: Install docker.io
  become: true
  apt:
    name: docker.io
    state: present
    update_cache: true


- name: Copy daemon.json from templates
  ansible.builtin.template:
    src: "./templates/daemon.json"
    dest: "/etc/docker"
    owner: root
    group: root
    mode: 0777
#     loop:
#       - {src: daemon.json, dest: /etc/docker}


- name: Start docker
  become: true
  ansible.builtin.systemd: 
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes


# - name: Copy kubelet.service file
#   ansible.builtin.template:
#     src: "./templates/10-kubeadm.conf"
#     dest: "/etc/systemd/system/kubelet.service.d"
    