---
- name: Remove swapfile from /etc/fstab to disable swap
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
     - swap
     - none


- name: Disable swap
  command: swapoff -a


- name: Install required dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - curl
      - software-properties-common
    state: present
    update_cache: yes
    force_apt_get: yes


- name: Add Apt signing keys for Docker and kube* tools, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  with_items:
     - https://packages.cloud.google.com/apt/doc/apt-key.gpg
     - https://download.docker.com/linux/ubuntu/gpg


- name: add kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    filename: 'kubernetes'

- name: add Docker GPG APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present


# - name: Create /etc/apt/sources.list.d/kubernetes.list directory
#   ansible.builtin.file:
#     path: /etc/apt/sources.list.d/kubernetes.list
#     state: directory
#     follow: yes

    
# - name: Copy kubernetes.list from templates
#   ansible.builtin.template:
#     src: "./templates/{{ item.src }}.sh"
#     dest: "{{ item.dest }}"
#     loop:
#       - {src: kubernetes.list, dest: /etc/apt/sources.list.d/kubernetes.list}
  # notify: Restart Controller services


- name: Install kube* tools
  become: true
  apt:
    name:
      - kubeadm=1.21.0-00
      - kubectl=1.21.0-00
      - kubelet=1.21.0-00
    state: present
    update_cache: yes
    force_apt_get: yes



# - name: Hold kubeadm
# - dpkg_selections:
#     name: kubeadm
#     selection: hold
# - dpkg_selections:
#     name: kubelet
#     selection: hold
# - dpkg_selections:
#     name: kubectl
#     selection: hold



- name: Install docker
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true


- name: Copy daemon.json from templates
  ansible.builtin.template:
    src: "./templates/daemon.json"
    dest: "/etc/docker"
    owner: root
    group: root
    mode: 0777



- name: Start docker
  become: true
  ansible.builtin.systemd: 
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes


# - name: Copy kubelet.service file
#   ansible.builtin.template:
#     src: "./templates/10-kubeadm.conf"
#     dest: "/etc/systemd/system/kubelet.service.d"

# add DNS names to /etc/host files
- name: add DNS names to /etc/hosts file
  template:
    src: ./templates/etc.hosts.j2
    dest: /etc/hosts
  register: etchostsupdate

# Update the /etc/hosts file with node names so our remote servers can talk to one another freely over SSH
# - name: update the /etc/hosts file
#   become: true
#   lineinfile:
#     path: "/etc/hosts"
#     regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
#     line: "{{ inventory_hostname }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
#     state: present
#     backup: yes
#   register: etchostsupdate
#   when: inventory_hostname != "item" or inventory_hostname == "item"
#   with_items: "{{ groups['all'] }}"

- name: Print /etc/hosts content
  ansible.builtin.debug:
    msg: "{{ etchostsupdate }}"
    